//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;

public class Logger
{
	private static Logger Instance {get; set;}

	private static string ContainerDirectory = "Logs";

	public String File {get; set;}

	private Logger ()
	{
	}
	
	public static Logger getInstance() {
		if(Instance == null) {
			if(!Directory.Exists(ContainerDirectory))
				Directory.CreateDirectory(ContainerDirectory);
			Instance = new Logger();
		}
		return Instance;
	}

	/// <summary>
	/// Write o in a file on one line.
	/// </summary>
	/// <param name="o">The object to write on the file.</param>
	public void Save(Object o) {
		if(Instance == null) {
			throw new Exception("File is not set !");
		}

		using (StreamWriter file = new StreamWriter(@"./" + ContainerDirectory +"/" + File, true))
		{
			file.WriteLine(o);
		}
    }
}

