//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

/// <summary>
/// Used only for serialization
/// </summary>
public class SerializableParameters
{
	// Simulation
	public int InitialPopulation;
	
	// Organisms
	public int BirhtDuration;
	public float PreAdultDuration;
	public float OrganismSight;
	
	// Death settings
	public float TimeBeforeRemove;
	public float DeathSmooth;
	
	// Movement settings
	public float MovementTurnRate;
	
	// Reproduction settings
	public float ApproachRate;
	public int NoNewChildDuration;

	public SerializableParameters ()
	{
		InitialPopulation = Parameters.InitialPopulation;
		BirhtDuration = Parameters.BirhtDuration;
		PreAdultDuration = Parameters.PreAdultDuration;
		OrganismSight = Parameters.OrganismSight;
		TimeBeforeRemove = Parameters.TimeBeforeRemove;
		DeathSmooth = Parameters.DeathSmooth;
		MovementTurnRate = Parameters.MovementTurnRate;
		ApproachRate = Parameters.ApproachRate;
		NoNewChildDuration = Parameters.NoNewChildDuration;
	}
}

