//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using GeneticLibrary.Interfaces;
namespace GeneticLibrary
{
	public class WFloat : IDeepClonable
	{
		public float Value {get; set;}

		public WFloat (float f)
		{
			Value = f;
		}

		public object DeepClone ()
		{
			return new WFloat(Value);
		}

		public override string ToString() {
			return Value.ToString();
		}
	}
}

