//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using GeneticLibrary.Mutations.Modifiers;
using GeneticLibrary.Collections;
using GeneticLibrary.Wrappers;


namespace GeneticLibrary
{
	public class SingleBlur : Blur
	{
		public SingleBlur(Set extensions, Set genes, float value) : base(extensions, genes, typeof(WFloat), value) { 
		}

		protected override object Compute(object o)
		{
			WFloat data = (WFloat)o;
			data.Value = new WFloat(mix(data.Value, Value)).Value;
			return data;
		}
	}
}

